[project]
name = "finance-visualizer"
version = "0.1.0"
description = "Making plots of financial data easy and fun!"
authors = [
    {name = "Dmitrii Mukhutdinov", email = "flyingleafe@gmail.com"},
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "tronscan-client",
    "plotly>=5.8.0",
    "notebook>=5.3",
    "ipywidgets>=7.5",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"